import { FormEvent, useState } from 'react'
import { Check, Cpu, Gauge, MessageSquare, Plus, Save, Trash2, Wifi } from 'lucide-react'
import { useFloodData } from '../hooks/useFloodData'

const sensorNames = ['Sensor 1 · Lower basin', 'Sensor 2 · Mid basin', 'Sensor 3 · Upper basin', 'Sensor 4 · Critical line'] as const
const sensorKeys = ['sensor1', 'sensor2', 'sensor3', 'sensor4'] as const

export default function Settings() {
  const { thresholds, setThresholds, smsRecipients, setSmsRecipients } = useFloodData()
  const [draftThresholds, setDraftThresholds] = useState(thresholds)
  const [recipients, setRecipients] = useState(smsRecipients)
  const [newRecipient, setNewRecipient] = useState('')
  const [saved, setSaved] = useState(false)
  const save = (event: FormEvent) => { event.preventDefault(); setThresholds(draftThresholds); setSmsRecipients(recipients); setSaved(true); window.setTimeout(() => setSaved(false), 2200) }

  return (
    <form onSubmit={save} className="space-y-6">
      <div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-slate-400"><Gauge size={14} /> Configuration</div><h1 className="mt-2 text-2xl font-extrabold tracking-tight text-slate-950 sm:text-3xl">Station settings</h1><p className="mt-1 text-sm text-slate-500">Configure alert thresholds and the people who receive SMS notifications.</p></div>
      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <div className="space-y-6">
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Gauge size={17} /></div><div><h2 className="text-sm font-bold text-slate-950">Water-level thresholds</h2><p className="mt-1 text-xs leading-5 text-slate-500">Set the sensor distance at which each level is triggered. Values are in centimeters.</p></div></div><div className="mt-6 space-y-5">{sensorKeys.map((key, index) => <div key={key}><div className="flex items-center justify-between gap-3"><label htmlFor={key} className="text-xs font-bold text-slate-700">{sensorNames[index]}</label><div className="flex items-center gap-1"><input id={key} type="number" min="1" max="100" value={draftThresholds[key]} onChange={(event) => setDraftThresholds({ ...draftThresholds, [key]: Number(event.target.value) })} className="w-16 rounded-lg border border-slate-200 bg-slate-50 px-2 py-1.5 text-right text-xs font-bold text-slate-900" /><span className="text-xs font-semibold text-slate-400">cm</span></div></div><input aria-label={`${sensorNames[index]} threshold`} type="range" min="1" max="100" value={draftThresholds[key]} onChange={(event) => setDraftThresholds({ ...draftThresholds, [key]: Number(event.target.value) })} className="mt-3 h-1.5 w-full accent-red-600" /><div className="mt-1 flex justify-between text-[10px] font-semibold text-slate-400"><span>1 cm</span><span>100 cm</span></div></div>)}</div></section>
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><MessageSquare size={17} /></div><div><h2 className="text-sm font-bold text-slate-950">SMS recipients</h2><p className="mt-1 text-xs leading-5 text-slate-500">These numbers receive an SMS when the station enters a possible flooding or severe state.</p></div></div><div className="mt-5 space-y-2">{recipients.map((recipient) => <div key={recipient} className="flex items-center justify-between rounded-xl bg-slate-50 px-3.5 py-3"><span className="text-sm font-semibold text-slate-700">{recipient}</span><button type="button" aria-label={`Remove ${recipient}`} onClick={() => setRecipients(recipients.filter((item) => item !== recipient))} className="rounded-lg p-1.5 text-slate-400 transition hover:bg-red-50 hover:text-red-600"><Trash2 size={15} /></button></div>)}</div><div className="mt-3 flex gap-2"><input value={newRecipient} onChange={(event) => setNewRecipient(event.target.value)} placeholder="+63 917 000 0000" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 placeholder:text-slate-400" /><button type="button" onClick={() => { if (newRecipient.trim()) { setRecipients([...recipients, newRecipient.trim()]); setNewRecipient('') } }} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3.5 py-2.5 text-xs font-bold text-white transition hover:bg-slate-700"><Plus size={15} /> Add</button></div></section>
        </div>
        <section className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Cpu size={17} /></div><div><h2 className="text-sm font-bold text-slate-950">Device information</h2><p className="mt-1 text-xs leading-5 text-slate-500">Read-only details for the connected field station.</p></div></div><div className="mt-6 divide-y divide-slate-100">{[['Device ID', 'FLD-042'], ['Controller', 'ESP32 DevKit V1'], ['Cellular modem', 'SIM800L · LTE ready'], ['GPS module', 'NEO-6M · GPS locked'], ['Firmware', 'v1.4.2'], ['Reporting interval', '5 minutes']].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><span className="text-xs font-semibold text-slate-500">{label}</span><span className="text-right text-xs font-bold text-slate-800">{value}</span></div>)}</div><div className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2.5 text-xs font-bold text-emerald-700"><Wifi size={14} /> Connected and reporting</div></section>
      </div>
      <div className="sticky bottom-16 z-10 flex items-center justify-end gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur lg:bottom-4">{saved && <span className="mr-auto inline-flex items-center gap-1.5 text-xs font-bold text-emerald-600"><Check size={15} /> Changes saved</span>}<button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-red-700"><Save size={15} /> Save settings</button></div>
    </form>
  )
}